
clear
N=200;M=200;
K=50; T=1; r=0.01; sigma=0.4;
S=zeros(N+1,1);
for i=1:N+1
    S(i)=100*(i-1)/N;% we set S [0,2K]
end
S=S';
U=G_Vector(N,K,S);

m = 9;
v = zeros(N+1,m);
for i = 1:m
    alpha = 0.1*i;
%    v(:,i) = FracEu_Put_Be(alpha, N, M, K, T, r, sigma, S, U);
    v(:,i) = FracAm_Put_OS(alpha, N, M, K, T, r, sigma, S, U);
end

fid = 1;
pname = './pic/alpha_wyss_am1.eps';
figure (fid)
hold on
%plot(S,U,'LineWidth',2);
plot(S,v(:,1),'*-', ...
     S,v(:,2),'*--', ...
     S,v(:,3),'*:', ...
     S,v(:,4),'*-.', ...
     S,v(:,5),'+-', ...
     S,v(:,6),':', ...
     S,v(:,7),'-.', ...
     S,v(:,8),'--', ...
     S,v(:,9),'-', ...
     'LineWidth',2,'MarkerSize',6);
xlim([48 52])
ylim([6 9])
legend('\alpha=0.1','\alpha=0.2','\alpha=0.3','\alpha=0.4',...
    '\alpha=0.5','\alpha=0.6','\alpha=0.7',...
    '\alpha=0.8','\alpha=0.9');
xlabel('Stock Price S');
ylabel('American Put Option Price V');
print('-f1', '-depsc2', pname);



fid = 2;
pname = './pic/alpha_wyss_am2.eps';
figure (fid)
hold on 
plot(S,v(:,1),'*-', ...
     S,v(:,2),'*--', ...
     S,v(:,3),'*:', ...
     S,v(:,4),'*-.', ...
     S,v(:,5),'+-', ...
     S,v(:,6),':', ...
     S,v(:,7),'-.', ...
     S,v(:,8),'--', ...
     S,v(:,9),'-', ...
     'LineWidth',2,'MarkerSize',6);
xlim([18.5 18.8])
legend('\alpha=0.1','\alpha=0.2','\alpha=0.3','\alpha=0.4',...
    '\alpha=0.5','\alpha=0.6','\alpha=0.7',...
    '\alpha=0.8','\alpha=0.9');
xlabel('Stock Price S');
ylabel('American Put Option Price V');
print('-f2', '-depsc2', pname);




fid = 3;
pname = './pic/alpha_wyss_am3.eps';
figure (fid)
hold on 
plot(S,v(:,1),'*-', ...
     S,v(:,2),'*--', ...
     S,v(:,3),'*:', ...
     S,v(:,4),'*-.', ...
     S,v(:,5),'+-', ...
     S,v(:,6),':', ...
     S,v(:,7),'-.', ...
     S,v(:,8),'--', ...
     S,v(:,9),'-', ...
     'LineWidth',2,'MarkerSize',6);
xlim([0.5 0.51])
legend('\alpha=0.1','\alpha=0.2','\alpha=0.3','\alpha=0.4',...
    '\alpha=0.5','\alpha=0.6','\alpha=0.7',...
    '\alpha=0.8','\alpha=0.9');
xlabel('Stock Price S');
ylabel('American Put Option Price V');
print('-f3', '-depsc2', pname);



fid = 4;
pname = './pic/alpha_wyss_am4.eps';
figure (fid)
hold on  
plot(S,v(:,1),'*-', ...
     S,v(:,2),'*--', ...
     S,v(:,3),'*:', ...
     S,v(:,4),'*-.', ...
     S,v(:,5),'+-', ...
     S,v(:,6),':', ...
     S,v(:,7),'-.', ...
     S,v(:,8),'--', ...
     S,v(:,9),'-', ...
     'LineWidth',2,'MarkerSize',6);
xlim([90 90.2])
legend('\alpha=0.1','\alpha=0.2','\alpha=0.3','\alpha=0.4',...
    '\alpha=0.5','\alpha=0.6','\alpha=0.7',...
    '\alpha=0.8','\alpha=0.9');
xlabel('Stock Price S');
ylabel('American Put Option Price V');
print('-f4', '-depsc2', pname);